# Enable validating this file
version: ~> 1.0

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

jobs:
  include:
    - script: ./test.sh
      name: "test"
    - install:
      - pip install -U platformio
      - platformio update
      script: ./build.sh
      name: "build"
