M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date Sat 30 Apr 2022 09:46:02 AM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-30T09:46:02-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X85.0Y-45.0
X85.0Y-65.0
X104.0Y-45.0
X104.0Y-65.0
T0
M30
