M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date Sun 14 May 2023 09:03:15 PM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-14T21:03:15-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X95.23Y-69.35
X106.66Y-69.35
T0
M30
